spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemonapicourse
    username: alien
    password: alien@1974
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
